# Generated by Django 5.1.1 on 2024-09-24 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyUsers',
            new_name='CompanyUser',
        ),
    ]
