# Generated by Django 5.1.1 on 2024-09-20 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='company.company'),
        ),
    ]
