# Generated by Django 5.1.1 on 2024-09-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_income_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyusers',
            name='report_perm',
            field=models.BooleanField(default=False),
        ),
    ]
