# Generated by Django 5.1.1 on 2024-09-20 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companyusers_report_perm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyusers'),
        ),
    ]
